### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by LinArcX** [LinArcX/kindd#10]
Writing a `.iso` to USB:
<a href="https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/5846037655687b2e16f733eff2ca593fbce108f4/process.png"><img src="https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/5846037655687b2e16f733eff2ca593fbce108f4/process.png"></a>

Settings(Universal theme):
<a href="https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/6f10355f7842f67aa51938ceb8bd1bae1c382216/settingsUniversal.png"><img src="https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/6f10355f7842f67aa51938ceb8bd1bae1c382216/settingsUniversal.png"></a>

**Comment by pcmagor** [comment]
> Writing a `.iso` to USB: ![](https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/5846037655687b2e16f733eff2ca593fbce108f4/process.png)
> 
> Settings(Universal theme): ![](https://gist.githubusercontent.com/LinArcX/4dde221ebf32b852586c65ecffdaa67f/raw/6f10355f7842f67aa51938ceb8bd1bae1c382216/settingsUniversal.png)
