### ISSUE TITLE
Console error at start: No GUI Items are shown

### ISSUE THREAD

**Issue by datalot-369** [LinArcX/kindd#12]
```
QQmlComponent: Component is not ready
qrc:/pages/main.qml:16:5: QML StackView: push: qrc:/pages/CreateISO.qml:5 module "Qt.labs.platform" version 1.1 is not installed
```

I have installed: `qml-module-qt-labs-platform:amd64 (5.11.3+dfsg-2)`, but the error persists.

![image](https://user-images.githubusercontent.com/21994415/87570213-3e400b00-c696-11ea-9980-eda6700b7d81.png)
> Screenshot of the GUI.

MX Linux 19.2 (Basically Debian Buster)

**Comment by datalot-369** [comment]
This appears to be an issue of the project itself, so it's needed to update the `Qt.labs.platform` implementation of the project to get further compatibility. [Posible reference here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958190).

**Comment by LinArcX** [comment]
@datalot-369 Hello. thanks for reporting. In void-linux i don't have same issue. Maybe it's related to how MX linux package it's stuff.

Edit: Actually `qt.labs` [introduced](https://doc.qt.io/qt-5/qtlabsplatform-index.html) in __Qt 5.8__, so i guess your version of qt is outdated. Currently i have 5.15.0_2 on my machine.
