### ISSUE TITLE
Window returning to offscreen location on weird screen setup

### ISSUE THREAD

**Issue by lalueck** [LinArcX/kindd#14]
i have kind of a weird screen setup with one long monitor and two normal ones, for some reason during the write process the window keeps returning to an off-screen location:
![image](https://user-images.githubusercontent.com/93910205/165127581-cdc25947-eec6-416c-b42a-9eb3dc9ea25c.png)
![image](https://user-images.githubusercontent.com/93910205/165128223-352c0b32-00eb-406d-bca6-97f7e2819f13.png)

Os: Arch
DE: KDE

**Comment by LinArcX** [comment]
Oh! such a weird problem.

Unfortunately i don't use KDE to reproduce your issue.

Meanwhile can you please run kindd from terminal to see if there is any warning or errors?

**Comment by lalueck** [comment]
after finally finding the time to test this i am not able to reproduce the issue of the window returning offscreen once flashing starts, it still loads offscreen once started tho.

startup terminal output here:
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Could not attach Keys property to:  LinArcxDialog_QMLTYPE_107(0x5651f62a43c0)  is not an Item
qrc:/pages/CreateISO.qml:484:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/pages/CreateISO.qml:476:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt/qml/QtQuick/Controls.2/Imagine/ProgressBar.qml:85:52: QML AnimatedImage: Error Reading Animated Image File qrc:/qt-project.org/imports/QtQuick/Controls.2/Imagine/images/progressbar-animation.webp
qml: model is empty
`

**Comment by LinArcX** [comment]
Sorry for late response. 

Which version of qt you are using on your machine?

I suppose it's qt6.
And I developed kindd with qt5.12.

Anyway, I'm not interested in qt anymore and prefer tui based apps nowadays.

Because of that I won't work on kindd anymore.

But it's open-source world. You can freely fork this project and maintain it.
