### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Aazerra** [LinArcX/kindd#15]
hi when i start kindd i getting this log in my terminal and it crash before i do anything in window
`pyro% kindd
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Could not attach Keys property to:  LinArcxDialog_QMLTYPE_97(0x55e5c0deda90)  is not an Item
qrc:/pages/CreateISO.qml:484:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/pages/CreateISO.qml:476:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt/qml/QtQuick/Controls.2/Imagine/ProgressBar.qml:85:52: QML AnimatedImage: Error Reading Animated Image File qrc:/qt-project.org/imports/QtQuick/Controls.2/Imagine/images/progressbar-animation.webp
terminate called after throwing an instance of 'std::regex_error'
  what():  Invalid start of '[x-x]' range in regular expression
zsh: IOT instruction (core dumped)  kindd`

**Comment by LinArcX** [comment]
Do you have?

`QT_QPA_PLATFORM=wayland`

**Comment by LinArcX** [comment]
Anyway look at:
https://github.com/LinArcX/kindd/issues/9#issuecomment-1238003767
