### ISSUE TITLE
App Missing An Icon

### ISSUE THREAD

**Issue by CanNuhlar** [LinArcX/Kindd#2]

**Comment by LinArcX** [comment]
Hi. There is a .svg file in:
https://github.com/LinArcX/Kindd/blob/master/appconf/kindd.svg
And also there is a .desktop file that use this svg:
https://github.com/LinArcX/Kindd/blob/master/appconf/kindd.desktop
If you create a package for kindd for your distro, you can use these files. For example i create a pkgbuild for arch users:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kindd-git
