### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by TahaPY** [LinArcX/Kindd#7]
```
[taha@Latitude ~]$ kindd
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
QQmlComponent: Component is not ready
qrc:/pages/main.qml:16:5: QML StackView: push: qrc:/pages/CreateISO.qml:449 Type ProgressBar unavailable
file:///usr/lib/qt/qml/QtQuick/Controls.2/Imagine/ProgressBar.qml:41 module "QtGraphicalEffects" is not installed

```
اروری که الان بعد نصب گرفتم
و نمیدونم از کجاست که درستش کنم و pull request بدم

**Comment by LinArcX** [comment]
You can try [kindd-git](https://aur.archlinux.org/packages/kindd-git/)
Also if you are interested in kindd, you can say to it's maintainer to update the dependency of project:
https://aur.archlinux.org/packages/kindd/
He should add `qt5-graphicaleffects` as new dependency.
