### ISSUE TITLE
Weird Debian behavior

### ISSUE THREAD

**Issue by d3acon15** [LinArcX/Kindd#8]
Is there any reason that if I am on a newer version of QTquick I would generate this error

./kindd
QQmlApplicationEngine failed to load component
qrc:/pages/main.qml:1 module "QtQuick" version 2.11 is not installed

If you need to know what version I am running of any specific module let me know but I was under the impression that with newer versions that they were backwards compatible and would run with the compiled features so this shouldn't be an issue on Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

**Comment by LinArcX** [comment]
Hi. I didn't use debian before and i don't have any idea about it's packages.
I'm developed kindd with Qt version 5.13.0 on void linux and it's works fine for me.(Also in arch)
