### ISSUE TITLE
Any further developement?

### ISSUE THREAD

**Issue by siduxdevil** [LinArcX/kindd#9]
Since there has been no commits for 3 months, the question arises whether further development is to be expected. If so, what should happen next? 

Background to my question is that I am writing an article on Kindd for a German Linux print magazine and would like to be able to advise my readers, if Kindd is worth the trouble of building the app. 

I built the app on KDE Neon and it took quite a while to get the dependencies right. No newbie would ever succeed with that.

Thanks for your work!

**Comment by LinArcX** [comment]
Hi. I have some ideas like porting this app for windows, but we don't have __dd__ in windows. So maybe I should re-implemnt the behavior of dd for windows.
Another improvement can be write windows iso. Currently if you try to create a Bootable device from windows iso, kindd can't do that.
Theses are my plans. But also I'm busy these days. So pull requests always be accepted. 

About packages for other distro, I only had arch, nixos, void before. 
So I can't package kindd for debian, fedora based distros. 

Again, if anybody like to send pr in theses areas, it'll be greate.

**Comment by siduxdevil** [comment]
I can list the dependencies now for Debian/Ubuntu, where KDE Neon and KaOS are probably the only distros shipping Qt 5.13.x at this point in time.

The dependencies (for KDE Neon, should be same/similar for Debian) are:
git
gcc
g++
make
qt5-default
libpolkit-qt5-dev
qml-module-qt-labs-platform
libqtquickcontrols2-5
qtquickcontrols2-5-dev
qml-module-qtgraphicaleffects
qtdeclarative5-dev

Maybe I will build a Debian package when I find the time.

**Comment by datalot-369** [comment]
It would be great if it becomes as Flatpak or AppImage. Please avoid Snappy at the most.

**Comment by Gibbz** [comment]
Id like to see support for imaging a dvd/partition to an iso file added!

**Comment by LinArcX** [comment]
@datalot-369 and @Gibbz pull-request are welcome.

**Comment by LinArcX** [comment]
For any person that still uses this project, I wanted to say that I won't work on kindd anymore.

These days I prefer simple solutions and using more tui tools.(actually I fell in love that how can I use dmenu with almost everything else for automation!) 

But, hey this is open source world. You __can__ and I __encourage__ you to fork my project and work on it, if you really like it.
